from flet import dropdown

def get_condicoes():

    condicoes = """1;VENDA A VISTA;SERRA_TALHADA
    2;DINHEIRO;SERRA_TALHADA
    3;CHEQUE PROPRIO;SERRA_TALHADA5 
    4;CHEQUE TERCEIRO;SERRA_TALHADA
    5;PIX;SERRA_TALHADA
    15;CHEQUE 15D;SERRA_TALHADA
    23;BOLETO ITAU 2D;SERRA_TALHADA
    24;BOLETO SICOOB;SERRA_TALHADA
    25;BOLETO ITAU 01PAJ;SERRA_TALHADA
    29;BOLETO 2D4;SERRA_TALHADA
    30;BOLETO 2D3;SERRA_TALHADA
    31;BOLETO 2D PF;SERRA_TALHADA
    32;BOLETO 2D PJ;SERRA_TALHADA
    33;BOLETO 2D1;SERRA_TALHADA
    34;BOLETO 2D2;SERRA_TALHADA
    35;BOLETO 6D GRUPO COMP;SERRA_TALHADA
    41;BOLETO ITAU 6DIAS;SERRA_TALHADA
    42;BOLETO 6 DIAS TOP;SERRA_TALHADA
    46;BOLETO 30D;SERRA_TALHADA
    47;BOLETO 10DGRUPOPAJEU;SERRA_TALHADA
    51;VENDA;SERRA_TALHADA
    52;BONIFICACAO;SERRA_TALHADA
    53;BRINDE;SERRA_TALHADA
    54;COMODATO;SERRA_TALHADA
    55;EMPRESTIMO;SERRA_TALHADA
    56;SIMPLES REMESSA;SERRA_TALHADA
    57;CONSIGNACAO;SERRA_TALHADA
    58;DEVOLUCAO AO FORNECE;SERRA_TALHADA
    59;TRANSFERENCIA;SERRA_TALHADA
    60;ACERTO;SERRA_TALHADA
    61;REMESSA P/DEPOSITO F;SERRA_TALHADA
    62;CONSUMO INTERNO;SERRA_TALHADA
    63;PERDA DE MERCADORIA;SERRA_TALHADA
    64;TROCA;SERRA_TALHADA
    65;VENDA AMBULANTE;SERRA_TALHADA
    66;BONIFICACAO CUSTO MK;SERRA_TALHADA
    70;OUTRAS SAIDAS;SERRA_TALHADA
    77;BOLETO ITAU 12DIAS;SERRA_TALHADA
    78;BOLETO ITAU 12D TOP;SERRA_TALHADA
    79;BOLETO 14D ITAU;SERRA_TALHADA
    80;BOLETO ITAU 1DIA;SERRA_TALHADA
    81;BOLETO 1D ITAU;SERRA_TALHADA
    82;BOLETO 30D VISITA;SERRA_TALHADA
    92;BOLETO 1D AVISTA;SERRA_TALHADA
    101;BOLETO ITAU PC;SERRA_TALHADA
    102;BOLETO ITAU 15DIAS;SERRA_TALHADA
    103;BOLETO AGRESTE;SERRA_TALHADA
    160;BOL BK;SERRA_TALHADA
    200;CARTAO CREDITO;SERRA_TALHADA
    201;BOLETO 30D ESPECIAL;SERRA_TALHADA
    202;CARTÃO DE DEBITO;SERRA_TALHADA
    203;BOL21D ITAU ESPECIAL;SERRA_TALHADA
    204;BOL 60D ESPECIAL;SERRA_TALHADA
    210;BOLETO ITAU 30D PAI;SERRA_TALHADA
    341;BOL ITAU 6D TESTE;SERRA_TALHADA
    850;PIX à Vista;SERRA_TALHADA
    853;Pague Direto;SERRA_TALHADA
    1;VENDA A VISTA;ARCOVERDE
    2;DINHEIRO;ARCOVERDE
    3;CHEQUE PROPRIO;ARCOVERDE
    4;CHEQUE TERCEIRO;ARCOVERDE
    5;PIX;ARCOVERDE
    15;CHEQUE 15D;ARCOVERDE
    24;BOLETO ITAU;ARCOVERDE
    25;BOLETO ITAU 01PAJ;ARCOVERDE
    29;BOLETO 2D4;ARCOVERDE
    30;BOLETO 2D3;ARCOVERDE
    31;BOLETO 2D PF;ARCOVERDE
    32;BOLETO 2D PJ;ARCOVERDE
    33;BOLETO 2D1;ARCOVERDE
    34;BOLETO 2D2;ARCOVERDE
    35;BOLETO 7 DIAS;ARCOVERDE
    36;BOLETO 15DIASTOP;ARCOVERDE
    41;BOLETO ITAU 6DIAS;ARCOVERDE
    42;BOLETO 6 DIAS TOP;ARCOVERDE
    47;BOLETO 10D PAJEU;ARCOVERDE
    51;VENDA;ARCOVERDE
    52;BONIFICACAO;ARCOVERDE
    53;BRINDE;ARCOVERDE
    54;COMODATO;ARCOVERDE
    55;EMPRESTIMO;ARCOVERDE
    56;SIMPLES REMESSA;ARCOVERDE
    57;CONSIGNACAO;ARCOVERDE
    58;DEVOLUCAO AO FORNECE;ARCOVERDE
    59;TRANSFERENCIA;ARCOVERDE
    60;ACERTO;ARCOVERDE
    61;REMESSA P/DEPOSITO F;ARCOVERDE
    62;CONSUMO INTERNO;ARCOVERDE
    63;PERDA DE MERCADORIA;ARCOVERDE
    64;TROCA;ARCOVERDE
    65;VENDA AMBULANTE;ARCOVERDE
    66;BONIFICACAO CUSTO MK;ARCOVERDE
    70;OUTRAS SAIDAS;ARCOVERDE
    77;BOLETO SICOOB 12DIAS;ARCOVERDE
    80;BOLETO 1 DIA ITAU;ARCOVERDE
    101;BOLETO ITAU PC;ARCOVERDE
    102;BOLETO SICOOB 15DIAS;ARCOVERDE
    200;CARTAO CREDITO;ARCOVERDE
    201;CARTÃO DÉBITO;ARCOVERDE
    203;BOL ITAU CARNAVAL;ARCOVERDE
    204;BOL 60D ESPECIAL;ARCOVERDE
    850;PIX à Vista;ARCOVERDE
    853;Pague Direto;ARCOVERDE
    1;VENDA A VISTA;SALGUEIRO
    2;DINHEIRO;SALGUEIRO
    3;CHEQUE PROPRIO;SALGUEIRO
    4;CHEQUE TERCEIRO;SALGUEIRO
    5;CREDITO EM CONTA;SALGUEIRO
    15;VENDA VALE;SALGUEIRO
    20;BOL 21 KRAFT;SALGUEIRO
    21;BOLETO 01CL5;SALGUEIRO
    22;BOLETO 01CES;SALGUEIRO
    23;BOLETO ITAU 5D;SALGUEIRO
    25;BOLETO 05PAD;SALGUEIRO
    26;BOLETO 05TOP;SALGUEIRO
    27;BOLETO 01PAJ;SALGUEIRO
    28;CARTAO DE CRÉDITO;SALGUEIRO
    29;CARTAO DE DEBITO;SALGUEIRO
    30;BOLETO 2D PFJ;SALGUEIRO
    31;BOLETO 2D PF;SALGUEIRO
    32;BOLETO 2D PJ;SALGUEIRO
    33;BOLETO 2D1;SALGUEIRO
    34;BOLETO 2D2;SALGUEIRO
    35;BOLETO 2D3;SALGUEIRO
    36;BOLETO 6D GRUPO COMP;SALGUEIRO
    40;BOLETO 7D;SALGUEIRO
    41;BOLETO IDC;SALGUEIRO
    41;BOLETO IDC;SALGUEIRO
    42;BOLETO IDC NL;SALGUEIRO
    43;BOLETO 21D VSNP;SALGUEIRO
    44;BOLETO 30 PRAZAO;SALGUEIRO
    45;BOLETO 60D ESPECIAL;SALGUEIRO
    46;BOL PC PAJEU;SALGUEIRO
    47;BOLETO 10D PAJEU;SALGUEIRO
    50;BOLETO BANCOOB 10D;SALGUEIRO
    51;VENDA;SALGUEIRO
    52;BONIFICACAO;SALGUEIRO
    53;BRINDE;SALGUEIRO
    54;COMODATO;SALGUEIRO
    55;EMPRESTIMO;SALGUEIRO
    56;SIMPLES REMESSA;SALGUEIRO
    57;CONSIGNACAO;SALGUEIRO
    58;DEVOLUCAO AO FORNECE;SALGUEIRO
    59;TRANSFERENCIA;SALGUEIRO
    60;ACERTO;SALGUEIRO
    61;REMESSA P/DEPOSITO F;SALGUEIRO
    62;CONSUMO INTERNO;SALGUEIRO
    63;PERDA DE MERCADORIA;SALGUEIRO
    64;TROCA;SALGUEIRO
    65;VENDA AMBULANTE;SALGUEIRO
    66;BONIFICACAO CUSTO MK;SALGUEIRO
    66;BONIFICACAO CUSTO MK;SALGUEIRO
    70;OUTRAS SAIDAS;SALGUEIRO
    81;BOL1D PARCEIRO AMBEV;SALGUEIRO
    82;BOLETO 30 D AGRESTE;SALGUEIRO
    83;BOLETO 21D BIN;SALGUEIRO
    84;BOLETO 30D SEL;SALGUEIRO
    85;BOLETO 15D SEL;SALGUEIRO
    86;BOLETO 30D ESP;SALGUEIRO
    112;DEPOSITO;SALGUEIRO
    850;PIX a Vista;SALGUEIRO
    853;Pague Direto;SALGUEIRO
    1;VENDA A VISTA;CEARA
    2;DINHEIRO;CEARA
    3;CHEQUE PROPRIO;CEARA
    4;CHEQUE TERCEIRO;CEARA
    6;BOLETO 1DD;CEARA
    7;BOLETO 1DD CN;CEARA
    8;BOLETO 2 DD;CEARA
    9;BOLETO 3 DD;CEARA
    11;BOLETO 6 DD;CEARA
    12;BOLETO 7 DD;CEARA
    13;BOLETO 10 DD;CEARA
    14;BOLETO 14 DD;CEARA
    15;BOLETO 15DD AS;CEARA
    16;BOLETO 15DD CN;CEARA
    17;BOLETO 21 PH/BK;CEARA
    18;BOLETO 1DD DIF;CEARA
    19;BOLETO 2 DD PFJ;CEARA
    20;BOLETO 1 DD PFJ;CEARA
    21;BOLETO 28 DD;CEARA
    22;BOLETO 2D1;CEARA
    23;BOLETO 3 DD LA;CEARA
    24;BOLETO 2 DD DPFJ;CEARA
    25;PIX QR CODE;CEARA
    26;BOLETO 15DD TS;CEARA
    26;BOLETO 15DD TS;CEARA
    27;BOLETO C.A;CEARA
    28;CARTÃO DE DEBITO;CEARA
    29;CARTÃO DE CREDITO;CEARA
    30;VENDA VALE;CEARA
    31;BOLETO 21DD RCC;CEARA
    32;BOLETO 14DD SELETO;CEARA
    33;BOLETO 6 DD ESP;CEARA
    34;BOLETO 30 DD DIZ;CEARA
    40;TED/DEP;CEARA
    51;VENDA;CEARA
    52;BONIFICACAO;CEARA
    53;BRINDE;CEARA
    54;COMODATO;CEARA
    55;EMPRESTIMO;CEARA
    56;SIMPLES REMESSA;CEARA
    57;CONSIGNACAO;CEARA
    58;DEVOLUCAO AO FORNECE;CEARA
    59;TRANSFERENCIA;CEARA
    60;ACERTO;CEARA
    61;REMESSA P/DEPOSITO F;CEARA
    62;CONSUMO INTERNO;CEARA
    63;PERDA DE MERCADORIA;CEARA
    64;TROCA;CEARA
    64;TROCA;CEARA
    65;VENDA AMBULANTE;CEARA
    66;BONIFICACAO CUSTO MK;CEARA
    70;OUTRAS SAIDAS;CEARA
    72;NOTA ASSINADA;CEARA
    100;DEPOSITO D;CEARA
    850;PIX à Vista;CEARA
    853;Pague Direto;CEARA
    1;VENDA A VISTA;GARANHUNS
    2;DINHEIRO;GARANHUNS
    3;CHEQUE PROPRIO;GARANHUNS
    4;CHEQUE TERCEIRO;GARANHUNS
    5;BOLETO 05D PAD;GARANHUNS
    6;BOLETO 06D PAD;GARANHUNS
    7;BOLETO 02D PAD;GARANHUNS
    8;PIX QR CODE;GARANHUNS
    9;BOLETO 06 EVENTO;GARANHUNS
    10;BOLETO 10D;GARANHUNS
    11;BOLETO 03D;GARANHUNS
    12;BOLETO A VISTA;GARANHUNS
    51;VENDA;GARANHUNS
    52;BONIFICACAO;GARANHUNS
    53;BRINDE;GARANHUNS
    54;COMODATO;GARANHUNS
    55;EMPRESTIMO;GARANHUNS
    56;SIMPLES REMESSA;GARANHUNS
    57;CONSIGNACAO;GARANHUNS
    58;DEVOLUCAO AO FORNECE;GARANHUNS
    59;TRANSFERENCIA;GARANHUNS
    60;ACERTO;GARANHUNS
    61;REMESSA P/DEPOSITO F;GARANHUNS
    62;CONSUMO INTERNO;GARANHUNS
    62;CONSUMO INTERNO;GARANHUNS
    63;PERDA DE MERCADORIA;GARANHUNS
    64;TROCA;GARANHUNS
    65;VENDA AMBULANTE;GARANHUNS
    66;BONIFICACAO CUSTO MK;GARANHUNS
    70;OUTRAS SAIDAS;GARANHUNS
    850;PIX a Vista;GARANHUNS
    853;Pague Direto;GARANHUNS"""
    
    return condicoes


def separar_condicoes():
    condicoes_linhas = get_condicoes().splitlines()
    condicoes = []


    for lin in condicoes_linhas:
        lin = lin.split(sep=';')
        condicao_cadastrada = { 
            'CODIGO' : lin[0].strip(),
            'DESCRICAO' : lin[1].strip(),
            'CIDADE' : lin[2].strip(),
        }
        condicoes.append(condicao_cadastrada)
    return condicoes


def get_revenda_condicoes(revenda):
    condicoes = separar_condicoes()
    condicoes_revenda = []

    if condicoes:
        for cond in condicoes:
            if cond['CIDADE'] == revenda:
                condicoes_revenda.append(cond)
    
    return condicoes_revenda


def get_condicao_codigo(condicao, revenda):
    codigos = get_revenda_condicoes(revenda)
    for cod in codigos:
        if cod['DESCRICAO'] == condicao:
            return cod['CODIGO']
    return None
